name: my-holdings

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile

    restart: unless-stopped

    environment:
      - SECONDARY_CURRENCY=HUF,Ft,hu-HU

    volumes:
      - ./apps/api/data:/app/data

    ports:
      - 9999:8080
